# Generated by Django 5.1.2 on 2024-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_website_link',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AddField(
            model_name='organization',
            name='company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('NONPROFIT', 'Non-Profit'), ('GOV', 'Government')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
