# Generated by Django 5.1.2 on 2024-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website_link',
        ),
        migrations.AddField(
            model_name='organization',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
