# Generated by Django 5.1.2 on 2024-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='username',
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
