# Generated by Django 5.1.2 on 2024-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
