# Generated by Django 5.1.2 on 2024-11-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_bounty_organization_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bounty',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='max_reward',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reward amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='min_reward',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum reward amount', max_digits=10, null=True),
        ),
    ]
