# Generated by Django 5.1.2 on 2024-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_rename_title_bounty_title_bounty_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='company',
        ),
    ]
