# Generated by Django 4.2.16 on 2024-11-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_rename_title_bounty_title_remove_bounty_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='organization.organization'),
        ),
    ]
