# Generated by Django 4.2.16 on 2024-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_bounty_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
