# Generated by Django 4.2.16 on 2024-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_bounty_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
