# Generated by Django 4.2.16 on 2024-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_bounty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='max_reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Maximum reward amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='min_reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimum reward amount', max_digits=10, null=True),
        ),
    ]
