# Generated by Django 4.2.16 on 2024-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_bounty_max_reward_alter_bounty_min_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
