# Generated by Django 5.1.2 on 2024-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_customadmin_email_alter_customadmin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='user_type',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
